Install latest version
source-foundry/hack-linux-installer pull request #1
Opened 2019-11-26 08:42 UTC by pschmitt

This adds the possibility to do the following:

```
./hack-linux-installer.sh latest
```

2019-11-28 21:17 UTC, chrissimpkins requested changes
This looks great Philipp!  Thank you very much for pushing this.  I really appreciate it.

Do you mind adding the quotes around `latest` as suggested in the review and we'll get this merged?  I fixed the CI testing and added a new test for this addition: https://semaphoreci.com/sourcefoundry/hack-linux-installer/branches/pull-request-1/builds/3

2019-11-28 21:17 UTC, chrissimpkins commented on hack-linux-installer.sh
> +#         Format the version number as vX.XXX or latest
Mind placing quotes around "latest" so that it is clear to use the verbatim string in the command?

2019-11-28 21:17 UTC, chrissimpkins commented on hack-linux-installer.sh
> +    echo "Please include a version number argument formatted as vX.XXX (or latest)"
Quotes around latest here too! Ty!

2019-11-29 08:31 UTC, pschmitt commented on hack-linux-installer.sh
> +#         Format the version number as vX.XXX or latest
Sure. Give me a sec.

2019-11-29 09:11 UTC, pschmitt commented
Done.

2019-11-29 16:02 UTC, chrissimpkins commented
Looks great!  Thank you very much for this.  I will merge it and push a new version tag/release.

2019-11-29 16:02 UTC, chrissimpkins approved these changes

2019-11-29 16:03 UTC, merged

2019-11-29 16:05 UTC, chrissimpkins commented
https://github.com/source-foundry/hack-linux-installer/releases/tag/v1.1.0